#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 001 - Fasting History Log

set -e

echo "========================================"
echo "FastTrack - Fasting History Log Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# GARMIN CONNECT IQ DEVELOPMENT SETUP
# ============================================

echo ""
echo "Setting up Garmin Connect IQ development environment..."
echo ""

# Check if Connect IQ SDK is installed
if ! command -v monkeyc &> /dev/null; then
    echo -e "${YELLOW}Warning: Garmin Connect IQ SDK not found in PATH${NC}"
    echo "Please ensure the SDK is installed and configured."
    echo "Download from: https://developer.garmin.com/connect-iq/sdk/"
fi

# Check if simulator is available
if ! command -v connectiq &> /dev/null; then
    echo -e "${YELLOW}Warning: Connect IQ Simulator not found in PATH${NC}"
    echo "The simulator is required for testing."
fi

# Navigate to project directory
cd "$(dirname "$0")/../../../FastTrack/FastTrack"

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: FastTrack Garmin Watch App"
echo "Target Device: approachs50"
echo ""
echo "To build and test:"
echo "  1. Open the project in VS Code or Eclipse"
echo "  2. Use 'MonkeyC: Build for Device' to compile"
echo "  3. Use 'MonkeyC: Run' to launch in simulator"
echo ""
echo "Implementation Plan:"
echo "  - Phase 1: Data Model & Storage (FastingHistory.mc)"
echo "  - Phase 2: Session Integration (modify FastingSession.mc)"
echo "  - Phase 3: History UI Views (create views and delegates)"
echo "  - Phase 4: Menu Integration (wire up navigation)"
echo "  - Phase 5: Verification (manual simulator testing)"
echo ""
echo "Ready for implementation!"
echo ""
