#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Garmin Glance Widget

set -e

echo "========================================"
echo "Garmin Connect IQ Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# BUILD GARMIN APP
# ============================================

echo ""
echo -e "${YELLOW}Building FastTrack Garmin App...${NC}"

cd ../../FastTrack/FastTrack

# Build the application
if monkeyc -d approachs50 -f monkey.jungle -o FastTrack.prg; then
    echo -e "${GREEN}Build successful!${NC}"
else
    echo -e "${RED}Build failed!${NC}"
    exit 1
fi

# ============================================
# START SIMULATOR
# ============================================

echo ""
echo -e "${YELLOW}Launching Garmin Connect IQ Simulator...${NC}"
echo "Note: The simulator is a GUI application and will open in a separate window."
echo ""
echo "To test the glance widget:"
echo "  1. Wait for simulator to load the app"
echo "  2. Right-click on the watch face in the simulator"
echo "  3. Select 'Add Glance' → 'FastTrack'"
echo "  4. View the glance widget on the watch face"
echo ""

# Launch simulator (this is a GUI app, so it won't block)
if command -v connectiq &> /dev/null; then
    connectiq &
    echo -e "${GREEN}Simulator launched!${NC}"
else
    echo -e "${RED}Error: connectiq command not found${NC}"
    echo "Please ensure Garmin Connect IQ SDK is installed and in your PATH"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Garmin Simulator: GUI application (no port)"
echo "  Device: Garmin Approach S50 (approachs50)"
echo ""
echo "Development workflow:"
echo "  1. Edit source files in FastTrack/FastTrack/source/"
echo "  2. Rebuild with: cd FastTrack/FastTrack && monkeyc -d approachs50 -f monkey.jungle -o FastTrack.prg"
echo "  3. Reload in simulator"
echo ""
